version: '3'
services:
    redis-sevice:
        image: 'redis'
    mySQL-sert:
        image: 'mysql'
        environment:
            MYSQL_ROOT_PASSWORD: root
    docker-app44:
        build: .
        ports:
          - "8080:8080"
        environment:
            - "SPRING_PROFILES_ACTIVE=dev"
